//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/AreaOfCube", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/AreaOfCubeResponse")]
        double AreaOfCube(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/AreaOfCube", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/AreaOfCubeResponse")]
        System.Threading.Tasks.Task<double> AreaOfCubeAsync(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/AreaOfRectangularPrism", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/AreaOfRectangularPrismResponse")]
        double AreaOfRectangularPrism(double l, double w, double h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/AreaOfRectangularPrism", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/AreaOfRectangularPrismResponse")]
        System.Threading.Tasks.Task<double> AreaOfRectangularPrismAsync(double l, double w, double h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/AreaOfCylinder", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/AreaOfCylinderResponse")]
        double AreaOfCylinder(double r, double h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/AreaOfCylinder", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/AreaOfCylinderResponse")]
        System.Threading.Tasks.Task<double> AreaOfCylinderAsync(double r, double h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/AreaOfCone", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/AreaOfConeResponse")]
        double AreaOfCone(double r, double l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IService1/AreaOfCone", ReplyAction="http://Microsoft.ServiceModel.Samples/IService1/AreaOfConeResponse")]
        System.Threading.Tasks.Task<double> AreaOfConeAsync(double r, double l);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MathClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MathClient.ServiceReference1.IService1>, MathClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double AreaOfCube(double a) {
            return base.Channel.AreaOfCube(a);
        }
        
        public System.Threading.Tasks.Task<double> AreaOfCubeAsync(double a) {
            return base.Channel.AreaOfCubeAsync(a);
        }
        
        public double AreaOfRectangularPrism(double l, double w, double h) {
            return base.Channel.AreaOfRectangularPrism(l, w, h);
        }
        
        public System.Threading.Tasks.Task<double> AreaOfRectangularPrismAsync(double l, double w, double h) {
            return base.Channel.AreaOfRectangularPrismAsync(l, w, h);
        }
        
        public double AreaOfCylinder(double r, double h) {
            return base.Channel.AreaOfCylinder(r, h);
        }
        
        public System.Threading.Tasks.Task<double> AreaOfCylinderAsync(double r, double h) {
            return base.Channel.AreaOfCylinderAsync(r, h);
        }
        
        public double AreaOfCone(double r, double l) {
            return base.Channel.AreaOfCone(r, l);
        }
        
        public System.Threading.Tasks.Task<double> AreaOfConeAsync(double r, double l) {
            return base.Channel.AreaOfConeAsync(r, l);
        }
    }
}
